version: '3'

services:
  db:
    build: database
    restart: always
    environment:
      POSTGRES_PASSWORD: 123

  pingpong:
    build: server
    command: "./wait-for-it.sh db:5432 -- python pingpong_server.py"
    volumes:
      - pubkey4:/pubkey
      - db_bay:/db
    depends_on:
      - db

  client:
    build: client
    command: "./wait-for-it.sh pingpong:50051 -- python pingpong_client.py FROMDB"
    volumes:
      - pubkey4:/pubkey
      - db_bay:/db
    depends_on:
      - pingpong

volumes:
  pubkey4:
  db_bay: